# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/configwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 226)
        MainWindow.setStyleSheet("background-color: rgb(240,240,240);\n"
"color: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 201, 31))
        self.label_2.setObjectName("label_2")
        self.historyCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.historyCheck.setGeometry(QtCore.QRect(170, 60, 70, 17))
        self.historyCheck.setText("")
        self.historyCheck.setObjectName("historyCheck")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 151, 16))
        self.label_4.setObjectName("label_4")
        self.correctCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.correctCheck.setGeometry(QtCore.QRect(170, 90, 70, 17))
        self.correctCheck.setText("")
        self.correctCheck.setObjectName("correctCheck")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 120, 151, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 150, 361, 21))
        self.label_6.setObjectName("label_6")
        self.completeInput = QtWidgets.QLineEdit(self.centralwidget)
        self.completeInput.setGeometry(QtCore.QRect(170, 120, 113, 20))
        self.completeInput.setStyleSheet("background-color: white;\n"
"border: none;\n"
"padding-top: 3px;\n"
"padding-bottom: 3px;\n"
"padding-left: 8px;\n"
"padding-right: 8px;\n"
"border-radius: 3px;")
        self.completeInput.setObjectName("completeInput")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 170, 361, 21))
        self.label_7.setObjectName("label_7")
        self.anwendenBtn = QtWidgets.QPushButton(self.centralwidget)
        self.anwendenBtn.setGeometry(QtCore.QRect(310, 120, 75, 23))
        self.anwendenBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.anwendenBtn.setStyleSheet("background-color: rgb(200,200,200);\n"
"border-radius: 3px;\n"
"cursor: pointer;")
        self.anwendenBtn.setObjectName("anwendenBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSchliessen = QtWidgets.QAction(MainWindow)
        self.actionSchliessen.setObjectName("actionSchliessen")
        self.menuDatei.addAction(self.actionSchliessen)
        self.menubar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(MainWindow)
        self.actionSchliessen.triggered.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Einstellungen"))
        self.label.setText(_translate("MainWindow", "Einstellungen"))
        self.label_2.setText(_translate("MainWindow", "Suchverlauf verwenden"))
        self.label_4.setText(_translate("MainWindow", "Autokorrektur verwenden"))
        self.label_5.setText(_translate("MainWindow", "Anzahl der Suchvorschläge"))
        self.label_6.setText(_translate("MainWindow", "Das Maximum ist 10, verwenden Sie 0 um Suchvorschläge zu deaktivieren."))
        self.label_7.setText(_translate("MainWindow", "Bestätigen mit ENTER"))
        self.anwendenBtn.setText(_translate("MainWindow", "Anwenden"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.actionSchliessen.setText(_translate("MainWindow", "Schliessen"))
